import React from "react";
import { GoDotFill } from "react-icons/go";
import { Helmet } from "react-helmet-async";

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <Helmet>
        <title>Privacy Policy | JobNirvana</title>
        <meta name="description" content="Our Privacy Policy explains how we collect, use, and protect your personal information when you use JobNirvana services." />
        <meta name="robots" content="noindex, follow" />
        <link rel="canonical" href={window.location.href} />
      </Helmet>
      <div className="bg-white rounded-3xl shadow-xl border border-gray-100 overflow-hidden">
        <header className="bg-gradient-to-r from-gray-900 to-gray-800 text-white py-8 px-8">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 45 46" fill="none">
                <path d="M35.6392 17.6831C37.1506 17.9768 37.7772 19.7964 36.7673 20.9584L21.9962 37.953C20.9862 39.115 19.097 38.7479 18.5957 37.2923L11.2635 16.0029C10.7621 14.5472 12.0246 13.0946 13.536 13.3883L35.6392 17.6831Z" fill="#8B94E7" />
                <path d="M9.10566 15.7428C8.33756 14.4085 9.30193 12.7431 10.8415 12.745L33.3582 12.7737C34.8978 12.7756 35.8579 14.4435 35.0864 15.7759L23.8033 35.2615C23.0318 36.5939 21.1073 36.5914 20.3392 35.2571L9.10566 15.7428Z" fill="#2D42FF" />
              </svg>
              <h1 className="text-2xl md:text-3xl font-bold">Privacy Policy</h1>
            </div>
            <p className="text-gray-400 text-sm">Last updated: June 23, 2024</p>
          </div>
        </header>

        <div className="p-8 md:p-12">
          <div className="prose prose-lg prose-blue max-w-none text-gray-600">
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use the
              Service and tells You about Your privacy rights and how the law protects
              You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By using
              the Service, You agree to the collection and use of information in
              accordance with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Interpretation and Definitions</h2>
            <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions shall
              have the same meaning regardless of whether they appear in singular or
              in plural.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to JobNirvana.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
              </li>
              <li>
                <strong>Country</strong> refers to: Andhra Pradesh, India
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Website.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
              </li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Collecting and Using Your Personal Data</h2>
            <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Types of Data Collected</h3>

            <h4 className="text-lg font-bold text-gray-700 mt-4 mb-2">Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but is
              not limited to: Usage Data.
            </p>

            <h4 className="text-lg font-bold text-gray-700 mt-4 mb-2">Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>
              Usage Data may include information such as Your Device's Internet
              Protocol address (e.g. IP address), browser type, browser version, the
              pages of our Service that You visit, the time and date of Your visit,
              the time spent on those pages, unique device identifiers and other
              diagnostic data.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <ul className="list-none pl-0">
              <li>
                By email: <a href="mailto:jobhunt2580@gmail.com" className="text-blue-600 hover:underline">jobhunt2580@gmail.com</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
